name: learn-github-actions
on: [push]
jobs:
  build-and-runs:
  name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build code
        run:  make 
      - name: test
        run: ./first_project